#!/bin/sh

### BEGIN INIT INFO
# Provides:          searchd
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: startup and helper script for the Sphinx search engine
# Description:       Sphinx - Free open-source SQL full-text search engine
### END INIT INFO

PREFIX=/usr/local

INDEXER="$PREFIX/bin/indexer"
SEARCHD="$PREFIX/bin/searchd"
CONF="$PREFIX/etc/sphinx-conf.php"
REINDEX_SCRIPTS_DIR="/usr/local/sphinx/cron"

PROG="searchd"
PID="/var/run/$PROG.pid"

RETVAL=0

test -x $SEARCHD || exit 0

# Include sphinx defaults if available
if [ -f /etc/default/sphinx ] ; then
  . /etc/default/sphinx
fi

set -e

. /lib/lsb/init-functions

start () {
  echo -n $"Starting $PROG: "
  start-stop-daemon --start --quiet --pidfile $PID \
    --exec $SEARCHD -- -c $CONF || true
  RETVAL=$?
  echo
  return $RETVAL
}

stop () {
  echo -n $"Stopping $PROG: "
  start-stop-daemon --stop --quiet --pidfile $PID \
    --exec $SEARCHD || true
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && rm -f $PID
}

index () {
  echo -n $"Reindexing all and rotate searchd:"
  $REINDEX_SCRIPTS_DIR/main.sh
}

delta () {
  echo -n $"Reindexing delta and rotate searchd:"
  $REINDEX_SCRIPTS_DIR/delta.sh
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status_of_proc -p $PID "$SEARCHD" searchd && exit 0 || exit $?
    ;;
  index)
    index
    delta
    ;;
  delta)
    delta
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|index|delta}" >&2
    exit 1
    ;;
esac

exit $RETVAL
